server:
  port: ${RANDOM_PORT:8133}  # 获取系统的环境变量
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
  servlet:
    context-path: /equipment
spring:
  gateway:
    globalcors:  #全局的跨域处理
      add-to-simple-url-handler-mapping: true  #解决options请求被拦截问题
      corsConfigurations:
        '[/**]':
          allowedHeaders: "*"   # 允许在请求头中携带的头信息
          allowedOrigins: "*"
          maxAge: 360000 # 这次跨域检测有效期
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTION
  profiles:
    active: equipment
  datasource:
    # primary:
    name: digital
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/digital?autoReconnect=true&connectTimeout=10000&socketTimeout=30000&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 500
  cloud:
    client:
      hostname: ${DEV_HOST}
  aop:
    auto: true
    proxy-target-class: false
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update,要不然每次重启都会新建表
    show-sql: true #打印执行的sql语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置数据库方言  记住必须要使用 MySQL5InnoDBDialect 指定数据库类型对应InnoDB  ;如果使用MySQLDialect 则对应的是MyISAM
logging:
  config: classpath:logback.xml
#icc:
#  host: 115.236.17.59:9021
#  clientId: CompanyName
#  clientSecret: 42bec152-8f04-476a-9aec-e7d616ff3cb3
